<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::whereNotNull('parent_id')->get();
        $brands = Brand::all();

        $products = [
            // الخضروات الطازجة
            [
                'name' => 'طماطم طازجة',
                'description' => 'طماطم حمراء طازجة مختارة بعناية، مثالية للسلطات والطبخ',
                'short_description' => 'طماطم طازجة عالية الجودة',
                'price' => 0.350,
                'compare_price' => 0.450,
                'stock_quantity' => 500,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => true,
                'is_new' => false,
                'is_on_sale' => true,
                'category' => 'خضروات طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'خيار طازج',
                'description' => 'خيار أخضر مقرمش ومنعش',
                'short_description' => 'خيار طازج مقرمش',
                'price' => 0.250,
                'stock_quantity' => 400,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => false,
                'is_new' => false,
                'category' => 'خضروات طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'بطاطس طازجة',
                'description' => 'بطاطس محلية طازجة ممتازة للقلي والطبخ',
                'short_description' => 'بطاطس طازجة محلية',
                'price' => 0.400,
                'compare_price' => 0.500,
                'stock_quantity' => 600,
                'weight' => 2.0,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'خضروات طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'بصل أحمر',
                'description' => 'بصل أحمر حلو ممتاز للسلطات',
                'short_description' => 'بصل أحمر طازج',
                'price' => 0.300,
                'stock_quantity' => 350,
                'weight' => 1.0,
                'unit' => 'kg',
                'category' => 'خضروات طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'فلفل أخضر حار',
                'description' => 'فلفل أخضر حار طازج',
                'short_description' => 'فلفل حار طازج',
                'price' => 0.450,
                'stock_quantity' => 200,
                'weight' => 0.5,
                'unit' => 'kg',
                'category' => 'خضروات طازجة',
                'brand' => 'صباح السالم',
            ],

            // فواكه طازجة
            [
                'name' => 'تفاح أحمر أمريكي',
                'description' => 'تفاح أحمر حلو ومقرمش من أمريكا',
                'short_description' => 'تفاح أحمر حلو',
                'price' => 1.200,
                'compare_price' => 1.500,
                'stock_quantity' => 300,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'فواكه طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'موز إكوادوري',
                'description' => 'موز إكوادوري طازج وغني بالبوتاسيوم',
                'short_description' => 'موز طازج غني بالبوتاسيوم',
                'price' => 0.650,
                'stock_quantity' => 450,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'فواكه طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'برتقال مصري',
                'description' => 'برتقال مصري طازج وعصيري',
                'short_description' => 'برتقال طازج عصيري',
                'price' => 0.800,
                'stock_quantity' => 400,
                'weight' => 1.0,
                'unit' => 'kg',
                'category' => 'فواكه طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'عنب أحمر بدون بذور',
                'description' => 'عنب أحمر حلو بدون بذور',
                'short_description' => 'عنب أحمر بدون بذور',
                'price' => 1.800,
                'stock_quantity' => 150,
                'weight' => 0.5,
                'unit' => 'kg',
                'is_new' => true,
                'category' => 'فواكه طازجة',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'فراولة طازجة',
                'description' => 'فراولة حمراء طازجة وحلوة',
                'short_description' => 'فراولة طازجة حلوة',
                'price' => 2.500,
                'compare_price' => 3.000,
                'stock_quantity' => 100,
                'weight' => 0.25,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'فواكه طازجة',
                'brand' => 'صباح السالم',
            ],

            // لحوم
            [
                'name' => 'لحم بقري طازج - كتف',
                'description' => 'لحم بقري طازج من كتف البقر، ممتاز للطبخ',
                'short_description' => 'لحم بقري طازج',
                'price' => 3.500,
                'stock_quantity' => 200,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'لحوم بقرية',
                'brand' => 'الفريج',
            ],
            [
                'name' => 'ستيك بقري طازج',
                'description' => 'ستيك بقري طازج عالي الجودة',
                'short_description' => 'ستيك بقري طازج',
                'price' => 5.500,
                'compare_price' => 6.500,
                'stock_quantity' => 80,
                'weight' => 0.5,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'لحوم بقرية',
                'brand' => 'الفريج',
            ],
            [
                'name' => 'دجاج كامل طازج',
                'description' => 'دجاج كامل طازج محلي',
                'short_description' => 'دجاج كامل طازج',
                'price' => 2.200,
                'stock_quantity' => 300,
                'weight' => 1.2,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'دواجن',
                'brand' => 'أمريكانا',
            ],
            [
                'name' => 'صدر دجاج منزوع العظم',
                'description' => 'صدر دجاج طازج منزوع العظم',
                'short_description' => 'صدر دجاج منزوع العظم',
                'price' => 2.800,
                'stock_quantity' => 250,
                'weight' => 1.0,
                'unit' => 'kg',
                'category' => 'دواجن',
                'brand' => 'أمريكانا',
            ],
            [
                'name' => 'لحم ضأن طازج',
                'description' => 'لحم ضأن طازج ممتاز للمندي والكبسة',
                'short_description' => 'لحم ضأن طازج',
                'price' => 4.500,
                'stock_quantity' => 100,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => false,
                'category' => 'لحوم ضأن',
                'brand' => 'الفريج',
            ],

            // ألبان
            [
                'name' => 'حليب كامل الدسم - المراعي',
                'description' => 'حليب كامل الدسم طازج 1 لتر',
                'short_description' => 'حليب كامل الدسم 1 لتر',
                'price' => 0.450,
                'stock_quantity' => 1000,
                'weight' => 1.0,
                'unit' => 'liter',
                'is_featured' => true,
                'category' => 'حليب وكريمة',
                'brand' => 'المراعي',
            ],
            [
                'name' => 'حليب خالي الدسم - المراعي',
                'description' => 'حليب خالي الدسم طازج 1 لتر',
                'short_description' => 'حليب خالي الدسم 1 لتر',
                'price' => 0.450,
                'stock_quantity' => 800,
                'weight' => 1.0,
                'unit' => 'liter',
                'category' => 'حليب وكريمة',
                'brand' => 'المراعي',
            ],
            [
                'name' => 'جبن كريمي - المراعي',
                'description' => 'جبن كريمي ناعم ممتاز للفطور',
                'short_description' => 'جبن كريمي ناعم',
                'price' => 1.200,
                'stock_quantity' => 400,
                'weight' => 0.2,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'جبن',
                'brand' => 'المراعي',
            ],
            [
                'name' => 'زبادي طبيعي - المراعي',
                'description' => 'زبادي طبيعي كامل الدسم',
                'short_description' => 'زبادي طبيعي',
                'price' => 0.350,
                'stock_quantity' => 600,
                'weight' => 0.15,
                'unit' => 'kg',
                'category' => 'زبادي ولبن',
                'brand' => 'المراعي',
            ],
            [
                'name' => 'بيض طازج - 30 حبة',
                'description' => 'بيض طازج محلي 30 حبة',
                'short_description' => 'بيض طازج 30 حبة',
                'price' => 1.800,
                'compare_price' => 2.200,
                'stock_quantity' => 500,
                'weight' => 1.8,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'بيض',
                'brand' => 'الكويتية',
            ],

            // مخبوزات
            [
                'name' => 'خبز عربي طازج',
                'description' => 'خبز عربي طازج يومياً',
                'short_description' => 'خبز عربي طازج',
                'price' => 0.150,
                'stock_quantity' => 2000,
                'weight' => 0.1,
                'unit' => 'piece',
                'is_featured' => true,
                'category' => 'خبز عربي',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'خبز توست أبيض',
                'description' => 'خبز توست أبيض ناعم',
                'short_description' => 'خبز توست أبيض',
                'price' => 0.450,
                'stock_quantity' => 800,
                'weight' => 0.4,
                'unit' => 'piece',
                'category' => 'خبز أوروبي',
                'brand' => 'السنبلة',
            ],
            [
                'name' => 'كرواسان زبدة',
                'description' => 'كرواسان زبدة طازج',
                'short_description' => 'كرواسان زبدة طازج',
                'price' => 0.350,
                'stock_quantity' => 300,
                'weight' => 0.08,
                'unit' => 'piece',
                'is_new' => true,
                'category' => 'كعك ومعجنات',
                'brand' => 'صباح السالم',
            ],
            [
                'name' => 'كيك شوكولاتة',
                'description' => 'كيك شوكولاتة طازج وغني',
                'short_description' => 'كيك شوكولاتة طازج',
                'price' => 2.500,
                'stock_quantity' => 100,
                'weight' => 0.5,
                'unit' => 'piece',
                'is_featured' => false,
                'category' => 'كيك وحلويات',
                'brand' => 'صباح السالم',
            ],

            // مشروبات
            [
                'name' => 'مياه معدنية - 12 زجاجة',
                'description' => 'مياه معدنية طبيعية 500 مل × 12 زجاجة',
                'short_description' => 'مياه معدنية 12 زجاجة',
                'price' => 1.500,
                'stock_quantity' => 1000,
                'weight' => 6.0,
                'unit' => 'pack',
                'is_featured' => true,
                'category' => 'مياه',
                'brand' => 'الصفوة',
            ],
            [
                'name' => 'عصير برتقال طازج',
                'description' => 'عصير برتقال طبيعي 100%',
                'short_description' => 'عصير برتقال طبيعي',
                'price' => 0.850,
                'stock_quantity' => 500,
                'weight' => 1.0,
                'unit' => 'liter',
                'category' => 'عصائر',
                'brand' => 'المراعي',
            ],
            [
                'name' => 'كوكا كولا - 6 علب',
                'description' => 'كوكا كولا 330 مل × 6 علب',
                'short_description' => 'كوكا كولا 6 علب',
                'price' => 1.200,
                'stock_quantity' => 800,
                'weight' => 2.0,
                'unit' => 'pack',
                'category' => 'مشروبات غازية',
                'brand' => 'كوكا كولا',
            ],
            [
                'name' => 'قهوة تركية - 250 جرام',
                'description' => 'قهوة تركية فاخرة 250 جرام',
                'short_description' => 'قهوة تركية فاخرة',
                'price' => 2.500,
                'stock_quantity' => 300,
                'weight' => 0.25,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'قهوة وشاي',
                'brand' => 'الكويتية',
            ],
            [
                'name' => 'شاي أحمر - 100 كيس',
                'description' => 'شاي أحمر ليبتون 100 كيس',
                'short_description' => 'شاي أحمر 100 كيس',
                'price' => 1.800,
                'stock_quantity' => 400,
                'weight' => 0.2,
                'unit' => 'box',
                'category' => 'قهوة وشاي',
                'brand' => 'نستله',
            ],

            // مواد غذائية
            [
                'name' => 'أرز بسمتي - 5 كجم',
                'description' => 'أرز بسمتي هندي فاخر 5 كجم',
                'short_description' => 'أرز بسمتي 5 كجم',
                'price' => 3.500,
                'compare_price' => 4.000,
                'stock_quantity' => 600,
                'weight' => 5.0,
                'unit' => 'kg',
                'is_featured' => true,
                'is_on_sale' => true,
                'category' => 'أرز وبقوليات',
                'brand' => 'السنبلة',
            ],
            [
                'name' => 'عدس أصفر - 1 كجم',
                'description' => 'عدس أصفر تركي عالي الجودة',
                'short_description' => 'عدس أصفر 1 كجم',
                'price' => 0.750,
                'stock_quantity' => 400,
                'weight' => 1.0,
                'unit' => 'kg',
                'category' => 'أرز وبقوليات',
                'brand' => 'السنبلة',
            ],
            [
                'name' => 'زيت زيتون بكر - 1 لتر',
                'description' => 'زيت زيتون بكر ممتاز 1 لتر',
                'short_description' => 'زيت زيتون بكر',
                'price' => 3.200,
                'stock_quantity' => 300,
                'weight' => 1.0,
                'unit' => 'liter',
                'is_featured' => true,
                'category' => 'زيوت وسمن',
                'brand' => 'زيتون',
            ],
            [
                'name' => 'سكر أبيض - 2 كجم',
                'description' => 'سكر أبيض ناعم 2 كجم',
                'short_description' => 'سكر أبيض 2 كجم',
                'price' => 1.000,
                'stock_quantity' => 800,
                'weight' => 2.0,
                'unit' => 'kg',
                'category' => 'سكر وملح وتوابل',
                'brand' => 'الأولى',
            ],
            [
                'name' => 'كاتشب هاينز - 500 جرام',
                'description' => 'كاتشب هاينز الأصلي 500 جرام',
                'short_description' => 'كاتشب هاينز',
                'price' => 1.100,
                'stock_quantity' => 500,
                'weight' => 0.5,
                'unit' => 'kg',
                'category' => 'صلصات وكاتشب',
                'brand' => 'نستله',
            ],
            [
                'name' => 'تونة معلبة - 4 علب',
                'description' => 'تونة معلبة في زيت 4 علب',
                'short_description' => 'تونة معلبة 4 علب',
                'price' => 1.800,
                'stock_quantity' => 700,
                'weight' => 0.6,
                'unit' => 'pack',
                'category' => 'معلبات',
                'brand' => 'أمريكانا',
            ],

            // مجمدات
            [
                'name' => 'بازلاء مجمدة - 400 جرام',
                'description' => 'بازلاء خضراء مجمدة 400 جرام',
                'short_description' => 'بازلاء مجمدة',
                'price' => 0.650,
                'stock_quantity' => 400,
                'weight' => 0.4,
                'unit' => 'kg',
                'category' => 'خضروات مجمدة',
                'brand' => 'أمريكانا',
            ],
            [
                'name' => 'ناجتس دجاج - 1 كجم',
                'description' => 'ناجتس دجاج مقلي مجمد 1 كجم',
                'short_description' => 'ناجتس دجاج مجمد',
                'price' => 2.800,
                'stock_quantity' => 250,
                'weight' => 1.0,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'أطعمة جاهزة',
                'brand' => 'أمريكانا',
            ],
            [
                'name' => 'آيس كريم فانيليا - 1 لتر',
                'description' => 'آيس كريم فانيليا كريمي 1 لتر',
                'short_description' => 'آيس كريم فانيليا',
                'price' => 1.500,
                'stock_quantity' => 200,
                'weight' => 1.0,
                'unit' => 'liter',
                'category' => 'آيس كريم',
                'brand' => 'المراعي',
            ],

            // عناية شخصية
            [
                'name' => 'شامبو بانتين - 400 مل',
                'description' => 'شامبو بانتين للشعر الجاف 400 مل',
                'short_description' => 'شامبو بانتين',
                'price' => 1.800,
                'stock_quantity' => 350,
                'weight' => 0.4,
                'unit' => 'liter',
                'category' => 'شامبو وبلسم',
                'brand' => 'نستله',
            ],
            [
                'name' => 'صابون دوف - 4 قطع',
                'description' => 'صابون دوف مرطب 4 قطع',
                'short_description' => 'صابون دوف 4 قطع',
                'price' => 1.200,
                'stock_quantity' => 500,
                'weight' => 0.4,
                'unit' => 'pack',
                'category' => 'صابون وغسول',
                'brand' => 'نستله',
            ],
            [
                'name' => 'معجون أسنان كولجيت - 150 جرام',
                'description' => 'معجون أسنان كولجيت 150 جرام',
                'short_description' => 'معجون أسنان كولجيت',
                'price' => 0.850,
                'stock_quantity' => 600,
                'weight' => 0.15,
                'unit' => 'piece',
                'category' => 'عناية بالأسنان',
                'brand' => 'نستله',
            ],

            // تنظيف
            [
                'name' => 'منظف صحون فيري - 750 مل',
                'description' => 'منظف صحون فيري 750 مل',
                'short_description' => 'منظف صحون فيري',
                'price' => 1.100,
                'stock_quantity' => 450,
                'weight' => 0.75,
                'unit' => 'liter',
                'category' => 'منظفات المطبخ',
                'brand' => 'نستله',
            ],
            [
                'name' => 'مسحوق غسيل تايد - 3 كجم',
                'description' => 'مسحوق غسيل تايد 3 كجم',
                'short_description' => 'مسحوق غسيل تايد',
                'price' => 3.500,
                'stock_quantity' => 300,
                'weight' => 3.0,
                'unit' => 'kg',
                'is_featured' => true,
                'category' => 'منظفات الغسيل',
                'brand' => 'نستله',
            ],
            [
                'name' => 'مناديل كلينكس - 6 علب',
                'description' => 'مناديل كلينكس 6 علب',
                'short_description' => 'مناديل كلينكس 6 علب',
                'price' => 2.200,
                'stock_quantity' => 400,
                'weight' => 0.6,
                'unit' => 'pack',
                'category' => 'مناديل ورقية',
                'brand' => 'نستله',
            ],
        ];

        foreach ($products as $productData) {
            $categoryName = $productData['category'];
            $brandName = $productData['brand'];

            $category = $categories->firstWhere('name', $categoryName);
            $brand = $brands->firstWhere('name', $brandName);

            if (!$category) {
                $this->command->warn("Category not found: {$categoryName}");
                continue;
            }

            $sku = 'SS-' . strtoupper(Str::random(8));

            Product::create([
                'name' => $productData['name'],
                'slug' => Str::slug($productData['name'] . '-' . $sku),
                'description' => $productData['description'],
                'short_description' => $productData['short_description'],
                'sku' => $sku,
                'price' => $productData['price'],
                'compare_price' => $productData['compare_price'] ?? null,
                'stock_quantity' => $productData['stock_quantity'],
                'stock_status' => 'in_stock',
                'weight' => $productData['weight'],
                'unit' => $productData['unit'],
                'category_id' => $category->id,
                'brand_id' => $brand?->id,
                'is_active' => true,
                'is_featured' => $productData['is_featured'] ?? false,
                'is_new' => $productData['is_new'] ?? false,
                'is_on_sale' => $productData['is_on_sale'] ?? false,
                'min_order_quantity' => 1,
                'max_order_quantity' => 50,
            ]);
        }

        $this->command->info('Created ' . count($products) . ' products successfully!');
    }
}
